---
- name: Install PuTTY on Windows Jumphost
  hosts: windows_jumphosts
  gather_facts: true

  tasks:
    - name: Install PuTTY using Chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: putty
        state: present
