---
- name: Install PuTTY on Windows Jumphost
  hosts: windows_jumphosts
  gather_facts: yes

  tasks:
    - name: Install PuTTY using Chocolatey
      win_chocolatey:
        name: putty
        state: present
